export const PTO_CONSTANTS = {
	SAFETY_LIMIT: 366,

	BRIDGE_GENERATION: {
		EFFICIENCY_COMPARISON_THRESHOLD: 0.1,
	},

	SCORING: {
		BASE_SCORE: 1,
		MULTI_DAY_BONUS: 1.5,
		EFFICIENCY: 0.6,
		TOTAL_VALUE: 0.4,
	},

	SELECTION_WEIGHTS: {
		HIGH_VALUE_THRESHOLD_DAYS: 3,
		HIGH_VALUE_THRESHOLD_EFFECTIVE: 9,
	},

	EFFICIENCY: {
		ACCEPTABLE: 2.5,
		MINIMUM: 2,
	},

	BRIDGE_SEARCH: {
		MIN_MULTI_DAY_SIZE: 2,
		MAX_MULTI_DAY_SIZE: 3,
	},
} as const;
