packages:
  - apps/*
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true
savePrefix: ""
overrides:
  "@opentelemetry/core": 2.11.0
minimumReleaseAge: 4320 # 3 days
blockExoticSubdeps: true
patchedDependencies:
  boneyard-js: patches/boneyard-js.patch
  vaul@1.1.2: patches/vaul@1.1.2.patch
