name = "forever-pto"
main = ".open-next/worker.js"
compatibility_date = "2025-11-25"
compatibility_flags = ["nodejs_compat", "enable_nodejs_process_v2"]
keep_names = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 0.2

[observability.traces]
enabled = true
head_sampling_rate = 0.2

[[tail_consumers]]
service = "forever-pto-tail"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "forever-pto-next-inc-cache"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "830b55c22c574287acebb51ca89b01f0"

[vars]
NEXT_PUBLIC_SITE_URL = "https://forever-pto.com"
NEXT_PUBLIC_CONTACT_EMAIL = "contact@forever-pto.com"


[env.development]
name = "forever-pto-development"

[[env.development.tail_consumers]]
service = "forever-pto-tail"

[env.development.observability]
enabled = true

[env.development.observability.logs]
invocation_logs = true
head_sampling_rate = 0.2

[env.development.observability.traces]
enabled = true
head_sampling_rate = 0.2

[env.development.vars]
NEXT_PUBLIC_SITE_URL = "https://development.forever-pto.com"
NEXT_PUBLIC_CONTACT_EMAIL = "contact@forever-pto.com"
NEXTJS_ENV = "development"
TURSO_DATABASE_URL = "libsql://forever-pto-development-fbuireu.aws-eu-west-1.turso.io"
CF_ACCESS_TEAM_DOMAIN = "https://fbuireu.cloudflareaccess.com"
CF_ACCESS_WORKERS_AUD = "a25b2ba0cd7b8ac4718cce10ba07ffa2a37301b2fe79cc00468f1606d5c15a26"
CF_ACCESS_PREVIEW_AUD = "66a0553e04ed5f8d2f4b6d48e73b11e671c912aa645ebf1b2dce04437e71c089"

[[env.development.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "forever-pto-next-inc-cache-dev"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "deae751b22674c0695fc1581161193dd"

[env.production]
name = "forever-pto"

[env.production.observability]
enabled = true

[env.production.observability.logs]
invocation_logs = true
head_sampling_rate = 0.2

[env.production.observability.traces]
enabled = true
head_sampling_rate = 0.2

[[env.production.tail_consumers]]
service = "forever-pto-tail"

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://forever-pto.com"
NEXT_PUBLIC_CONTACT_EMAIL = "contact@forever-pto.com"
NEXTJS_ENV = "production"
TURSO_DATABASE_URL = "libsql://forever-pto-fbuireu.aws-eu-west-1.turso.io"
CF_ACCESS_TEAM_DOMAIN = "https://fbuireu.cloudflareaccess.com"

[[env.production.routes]]
pattern = "forever-pto.com/*"
zone_name = "forever-pto.com"

[[env.production.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "forever-pto-next-inc-cache"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "830b55c22c574287acebb51ca89b01f0"
