// Re-exports from animate-ui base-ui dialog — maintains backward compat with shadcn API
export {
  Dialog,
  DialogTrigger,
  DialogClose,
  DialogContent,
  DialogPopup,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  type DialogProps,
  type DialogTriggerProps,
  type DialogCloseProps,
  type DialogContentProps,
  type DialogPopupProps,
  type DialogHeaderProps,
  type DialogFooterProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
} from 'src/components/animate-ui/base/dialog';
