export const PTO_CONSTANTS = {
  SAFETY_LIMIT: 30,

  BRIDGE_GENERATION: {
    MIN_EFFICIENCY_FOR_ALTERNATIVES: 2,
    MIN_EFFICIENCY_FOR_BALANCED: 2,
    MIN_EFFICIENCY_FOR_OPTIMIZED: 2.5,
    EFFICIENCY_COMPARISON_THRESHOLD: 0.1,
  },

  DAY_GROUPING: {
    MAX_DAYS_DIFF: 7,
    MAX_DAYS_DIFF_FOR_RANGE: 4,
    MAX_SEARCH_DISTANCE: 5,
  },

  SCORING: {
    BASE_SCORE: 1,
    BALANCED_MULTI_DAY: 1.2,
    PROXIMITY_BONUS: 3,
    MULTI_DAY_BONUS: 1.5,
    EFFICIENCY: 0.6,
    TOTAL_VALUE: 0.4,
  },

  SELECTION_WEIGHTS: {
    HIGH_VALUE_THRESHOLD_DAYS: 3,
    HIGH_VALUE_THRESHOLD_EFFECTIVE: 9,
  },

  EFFICIENCY: {
    PERFECT: 4,
    GOOD: 3,
    ACCEPTABLE: 2.5,
    MINIMUM: 2,
    MINIMUM_FOR_SINGLE_BRIDGE: 3,
    },
  
  BRIDGE_SEARCH: {
    MIN_MULTI_DAY_SIZE: 2,
    MAX_MULTI_DAY_SIZE: 3,
  },
} as const;
