import type { Metadata } from 'next';
import type { Locale } from 'next-intl';

interface GenerateMetadataParams {
  params: Promise<{ locale: Locale }>;
}

export async function generateMetadata({ params }: GenerateMetadataParams): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  };
}
