"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _calendar_list from './calendar-list.bones.json'
import _summary from './summary.bones.json'
import _planner_panel from './planner-panel.bones.json'
import _alternatives_manager from './alternatives-manager.bones.json'
import _pto_status from './pto-status.bones.json'

configureBoneyard({"color":"#fff8ee","darkColor":"#1e1914","animate":"shimmer","shimmerColor":"#fffdf8","darkShimmerColor":"#241e18","transition":true})

registerBones({
  "calendar-list": _calendar_list,
  "summary": _summary,
  "planner-panel": _planner_panel,
  "alternatives-manager": _alternatives_manager,
  "pto-status": _pto_status,
})
