'use client';
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';
import { configureBoneyard } from 'boneyard-js/react';

import _alternatives_manager from './alternatives-manager.bones.json';
import _calendar_list from './calendar-list.bones.json';
import _pto_status from './pto-status.bones.json';
import _summary from './summary.bones.json';

configureBoneyard({
  color: '#f0e2be',
  darkColor: '#2b241e',
  animate: 'shimmer',
  shimmerColor: '#fff8ee',
  darkShimmerColor: '#3d3228',
  transition: true,
});

registerBones({
  'alternatives-manager': _alternatives_manager,
  'pto-status': _pto_status,
  'calendar-list': _calendar_list,
  summary: _summary,
});
