export const PTO_CONSTANTS = {
	SAFETY_LIMIT: 366,

	BRIDGE_GENERATION: {
		EFFICIENCY_COMPARISON_THRESHOLD: 0.1,
	},

	EFFICIENCY: {
		MINIMUM: 2,
		BLOCK_MINIMUM: 1.4,
	},

	BRIDGE_SEARCH: {
		MIN_MULTI_DAY_SIZE: 2,
		MAX_MULTI_DAY_SIZE: 5,
	},

	SELECTION: {
		GROUPED_MAX_BLOCK_DAYS: 16,
		BALANCED_MAX_BLOCK_DAYS: 9,
		RANK_TOLERANCE: 1e-9,
	},

	ALTERNATIVES: {
		MIN_DIFFERENCE: 0.25,
		RUNS_PER_ALTERNATIVE: 6,
	},

	METRICS: {
		LONG_BLOCK_MINIMUM_DAYS: 3,
		LONG_WEEKEND_MINIMUM_DAYS: 3,
		REST_BLOCK_SEPARATION_DAYS: 7,
		STREAK_SCAN_MARGIN_DAYS: 7,
	},
} as const;
