name: Cleanup - Development

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup development workers
    runs-on: ubuntu-latest
    steps:
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: workers delete development-pr-${{ github.event.pull_request.number }} --force
